version: '3.1'

services:
  db:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=icrawler
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3sEm9PyNvvByHHZ
    ports:
      - "6432:5432"
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  scrapyd:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    entrypoint: ["sh", "-c", "cd /app/scrapy_app && scrapyd"]
    ports:
      - "6800:6800"
